context:
  version: "3.13.0"

package:
  name: panache
  version: ${{ version }}

source:
  url: https://github.com/jolars/panache/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 65b5b9da0ea2f7cf04e38e003102683bcaeca97e4c5df5dc4f77eda5fd7568b5

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # build main app and generate license data
      - cargo auditable install --path=. --root=($prefix) --no-track --locked --bin=panache
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
      # copy shell completion files and man page
      - mkdir ($prefix)/share/bash-completion/completions ($prefix)/share/fish/vendor_completions.d ($prefix)/share/zsh/site-functions ($prefix)/share/man/man1
      - cp target/completions/panache.bash ($prefix)/share/bash-completion/completions/panache
      - cp target/completions/panache.fish ($prefix)/share/fish/vendor_completions.d/panache.fish
      - cp target/completions/_panache     ($prefix)/share/zsh/site-functions/_panache
      - cp target/man/panache.1            ($prefix)/share/man/man1/panache.1

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - nushell

tests:
  - script:
      - panache --help
      - panache --version
  - package_contents:
      bin:
        - panache
      files:
        - if: unix
          then:
            - share/bash-completion/completions/panache
            - share/fish/vendor_completions.d/panache.fish
            - share/zsh/site-functions/_panache
            - share/man/man1/panache.1
        - if: win
          then:
            - Library/share/bash-completion/completions/panache
            - Library/share/fish/vendor_completions.d/panache.fish
            - Library/share/zsh/site-functions/_panache
            - Library/share/man/man1/panache.1
      strict: true

about:
  summary: A language server, formatter, and linter for Markdown, Quarto, and R Markdown, built in Rust with a lossless CST parser and support for external formatters and linters on code blocks.
  description: |
    Panache is a language server, formatter, and linter for Markdown, Quarto,
    and R Markdown. It is built for fast, reliable formatting, linting, and
    language services across syntax that many generic Markdown tools struggle
    with, including fenced divs, grid tables, definition lists, citations, and
    inline footnotes.

    Panache is designed to follow Pandoc’s syntax closely and cover its full
    range of Markdown dialects (flavors) and extensions, to be able to handle
    anything from simple CommonMark to complex Quarto documents with embedded
    code chunks and fenced divs. It is flexible and can be used in your editor,
    on the command line, and in CI, with consistent behavior across all
    environments.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://panache.bz/
  repository: https://github.com/jolars/panache

extra:
  recipe-maintainers:
    - salim-b
